services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: backend
      POSTGRES_HOST_AUTH_METHOD: trust
    # networks:
    #   - form_hub_network

  redis:
    image: redis:6.2.5-alpine
    # networks:
    #   - form_hub_network

  backend:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    environment:
      DATABASE_URL: postgres://postgres@postgres/backend
      PORT: 8000
      REDIS_HOST: redis
    # networks:
    #   - form_hub_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   form_hub_network:
#     external: true